// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package shared

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuctionhouseClient is the client API for Auctionhouse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionhouseClient interface {
	Bid(ctx context.Context, in *BidAmount, opts ...grpc.CallOption) (*Empty, error)
	Result(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Outcome, error)
}

type auctionhouseClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionhouseClient(cc grpc.ClientConnInterface) AuctionhouseClient {
	return &auctionhouseClient{cc}
}

func (c *auctionhouseClient) Bid(ctx context.Context, in *BidAmount, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Auctionhouse/Bid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionhouseClient) Result(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/Auctionhouse/Result", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionhouseServer is the server API for Auctionhouse service.
// All implementations must embed UnimplementedAuctionhouseServer
// for forward compatibility
type AuctionhouseServer interface {
	Bid(context.Context, *BidAmount) (*Empty, error)
	Result(context.Context, *Empty) (*Outcome, error)
	mustEmbedUnimplementedAuctionhouseServer()
}

// UnimplementedAuctionhouseServer must be embedded to have forward compatible implementations.
type UnimplementedAuctionhouseServer struct {
}

func (UnimplementedAuctionhouseServer) Bid(context.Context, *BidAmount) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedAuctionhouseServer) Result(context.Context, *Empty) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedAuctionhouseServer) mustEmbedUnimplementedAuctionhouseServer() {}

// UnsafeAuctionhouseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionhouseServer will
// result in compilation errors.
type UnsafeAuctionhouseServer interface {
	mustEmbedUnimplementedAuctionhouseServer()
}

func RegisterAuctionhouseServer(s grpc.ServiceRegistrar, srv AuctionhouseServer) {
	s.RegisterService(&Auctionhouse_ServiceDesc, srv)
}

func _Auctionhouse_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidAmount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionhouseServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auctionhouse/Bid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionhouseServer).Bid(ctx, req.(*BidAmount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auctionhouse_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionhouseServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auctionhouse/Result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionhouseServer).Result(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Auctionhouse_ServiceDesc is the grpc.ServiceDesc for Auctionhouse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auctionhouse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Auctionhouse",
	HandlerType: (*AuctionhouseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bid",
			Handler:    _Auctionhouse_Bid_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _Auctionhouse_Result_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auctionhouse.proto",
}
